language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.gradle/nodejs/"
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: xNFrOSXoBue5VXwFB604Lx40SxXJfJyZ6OAbru6MEPZ01VBbC70Zh80r14Vv8u74D9FEd+lCLZaLoHkP+4fs4S6SlnFTbnNhNyyczgGLyqY/JKSG7cDpr/NUiL3/7i49wL5TBIorQiXmBrZoVTj4sSIymlWi9cMIM8TL6ITgzZcR1PhT2VF6b9B7leAVo31sjYf+NIgWgheVBoT2YOYzp1CjelgYAHM52i4PrOY+7YA0en7mQxWBBXgJjpBB74eBYmODQv27MsxZMUz0BRT4PCrVAN/pSPIr3CpUyo2U8Qz11g/Cx7ufsIUCRkvtOT5JqBmlgJ0cfUCe/3TMfVr3D9AkaBhzs7bVLGplxy1/31+YsytE3a1Aa+1pay9TQbOZfyh0zt8RbYUn5C2fvZ6NRH/5+/y2Q7nq7G8+1yVolvmDcljC+QR2qQO571Q6jv7OHgBX/127zwGy3nbJxj2in9zXXk/XExWARjFlEc4dXFgHYR5XXoTuD0/S5Ow0UUgRfR2FxlsDvVeBI8yjfUX+b6Q7u7qLhi2Nxho9aCHUVVaaSyOn1Xu+/ZyzC2TK98VVk/1kFjPjWzXufniT3/oAB8vObR2fGRxzDHNAnToQjAF8hQiNxcU3PHi93MKlmAin6jBIQKK9HJkKjGCw17fWc/EMv40v/tCigNYfcrtitGk=
  app: thedungeonguide
  on:
    repo: Avabin/TheDungeonGuide
notificaions:
  on_success: change
  on_failure: always
  slack:
    secure: GXbqCX1FtMlrjyk8g2qwVzB1bAVuSwH4slc+ivKvaVRk654+/vuP43QNGV4vNkAwI3NMBm301/ItAhvprCwzVAk2DQ3wdlyoVIWpADNepJ6ZyIkgHV7U+TcRfUotOXS65+hCil/YgBwtvokcQalxAvM70mZgxb0zb2+xDkbryKhRQ02UYPyXQeMHpY4i+hc2/aa7vPZyXg7HOjPTkV68Uyxlgg6lXVn9KlaPas+IVpAzaYzwrXfO2jUCNNsGQRloR9Wy0llU+3eWonLnA3+lWWyF65R0sJGkpGCFAfq0FiURnpX0rCpDvIQHZKR1SZXwESVP3w/mp5NggFeXOOUGtMnMLZ9pGfb1BIr5RkQYJb6t5qgtUXRmnxOdhP2DCeZM2cnIXNxk2gVLlLtGRcXXhD6Tt55gna5RcRoObS6n7a4F3ed5EdslQA9Lz9bx7p6MbBECD1NF6WUNTTwbz9e92snsJRyAiRRO9YoVI/7vPwJepd/RICLpvfOWqFEW3sSZH9Aerw9+sDyfuovhxUwx/bS1ZStrO+XpUQ2o0tOlp262WUwmDGTIJvIq0xPGcFeLLa/BkkLv7ORzJcjnaHKYdiVngB5k9IL+j2lnoAsTIxSFOqjCgIHP2xaN+RZAaAvKV64weIUe6vwr++8fpLkSGNU1zMXrOz1hyACPaiE3WFI=
