language: java
jdk:
- oraclejdk8
services:
- postgresql
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_script:
- psql -c 'create database tdg;' -U postgres
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: heroku
  api_key:
    secure: FzD9KxGozsx4iH6Kjjc2vlpd9FR0JLosLOwm1QbWlSXucAW1ajuBOBe0sv/Qc04LW6orL7EQYqlVszDb2Vw4tt07OWB6LoB/N2GiMTgdUVKZ0RAOxKCty2RmE5W2pV2pzYR9ITnDWwV2Thjb8AnPHcOWB4ejR8FdeuY8RSQrLS15ihtwvg33WhGiO39ogewQ0RaXhUWr7wtVkSIrGYI4vLB+3CYUXRToAFuSEuglrCtXUJj7hXHCzPpJog4rxUpObLgkqWDbkxo1ERQBUCSqiusK7EcsaQ9araruo7i9nL6Pk/oeyPcYRvGXorZvlu56om5t39OJTB1wOKxfFpHSckhzK2g6zyvLXlI+sK4VI56H7Gmacfus9Xml3Smmcs1x5OEJcmbdKPPMxXWe6195oQQ7kZtjKPf2DsLFZDRO8Zqwhs43AtpnQcCH0C9FwI1S7GCx8gHrN3b15c3WkFHDqgAFMOlwp74j8HXBr2iBraFDYbErG37P1bFQpw2cGhi0/kGhXCBzrTFRbNhv1AChVeAnAc8gpULvhNoukDvWUszwamRuM+xqZQvd/gAPVm40AKC6xWuff00uOhbFiAv2367LeIiN4L+qCOmjj14sBSsJWsndEBVjbffHEAcubWnCaO3MY/9cH7GlXW2ygn3/iR33m1jn3t/tRgXzhGtZKlM=
  app: TheDungeonGuide
  on:
    repo: Avabin/TheDungeonGuide
