language: java
jdk:
- oraclejdk8
python:
- "3.6"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.gradle/nodejs/"
  - node_modules
script:
- python3 python-tests/src/test_rest.py
deploy:
  provider: heroku
  api_key:
    secure: xNFrOSXoBue5VXwFB604Lx40SxXJfJyZ6OAbru6MEPZ01VBbC70Zh80r14Vv8u74D9FEd+lCLZaLoHkP+4fs4S6SlnFTbnNhNyyczgGLyqY/JKSG7cDpr/NUiL3/7i49wL5TBIorQiXmBrZoVTj4sSIymlWi9cMIM8TL6ITgzZcR1PhT2VF6b9B7leAVo31sjYf+NIgWgheVBoT2YOYzp1CjelgYAHM52i4PrOY+7YA0en7mQxWBBXgJjpBB74eBYmODQv27MsxZMUz0BRT4PCrVAN/pSPIr3CpUyo2U8Qz11g/Cx7ufsIUCRkvtOT5JqBmlgJ0cfUCe/3TMfVr3D9AkaBhzs7bVLGplxy1/31+YsytE3a1Aa+1pay9TQbOZfyh0zt8RbYUn5C2fvZ6NRH/5+/y2Q7nq7G8+1yVolvmDcljC+QR2qQO571Q6jv7OHgBX/127zwGy3nbJxj2in9zXXk/XExWARjFlEc4dXFgHYR5XXoTuD0/S5Ow0UUgRfR2FxlsDvVeBI8yjfUX+b6Q7u7qLhi2Nxho9aCHUVVaaSyOn1Xu+/ZyzC2TK98VVk/1kFjPjWzXufniT3/oAB8vObR2fGRxzDHNAnToQjAF8hQiNxcU3PHi93MKlmAin6jBIQKK9HJkKjGCw17fWc/EMv40v/tCigNYfcrtitGk=
  app: thedungeonguide
  on:
    repo: Avabin/TheDungeonGuide
notifications:
  slack:
    secure: PryuPxRkPIuigMdh39SuvTwobYybtIX6zbvLgP2dp5EXK7WUzM3rNoUdNUi+hLT0fgYnmvqZfb29P7rnTXAMqZJmkw15oSi+3LmcOJt6vQFh777bKPvzNlYZTyqqANlPxHkU5wfPw4bTwAcX0JYaGs1bA9dqWbsjRRxcvX3pSdY1/9b3JwFtEFBbgb4qUz4C4hGsPOfsEXOGHQ/rbfWOFTzNBAwJYPlQFH/g82G0Gm7pEc8WETTynR3EPd/2YXptPKQTl0wIVZKmt2LDi64d1RZxYo7AlcAcHgjdOBSp/a7lm83Vd8A00g+ABTNKKfrs+e7hNTDxg6FsJVcrp82CarIGzdbbzr6wP3qJuGL1S6eJQ69bLipHUOGx3a1AOgB5bNEa2YwN5ZWHAhPuS2ecjQTBUzE4C3V5YSLNXvCUbg96coHSl2h01+FJiy1362j/pzZi2zwxVSg+EeBNvzAelioBp7RNH/2hWIhl5NC2mnlFhi7iCb1E+ukQiNm58RLNK6V9jMcOAuYhV38pV9r3dLM23Uw0i1yQjwudCtIligqRiWjHQ2aWnwRTm0i/pqKhgADkQbDar35hRZBdB+kjxQao3jnR+Kf0inY8P4yJBoGhIpb83i5C+o0B77A6kATe9lMJteb7oPxw94Oo3y4RtsVJhvq/AJJbruz7IUXDMQ4=
