language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.gradle/nodejs/"
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: LqiOfyKgXza6NyDcQHGYnMnx3qCgfuFAaeP5gXuapT0wZzvkkiovC6xo3ABp9TwxsNjejTv7BtDfdDGbrR3gNeRLmNji/1c7w7d080gZoRkJvJffU9Ww3W9keV/cS+4DBVKXdsfVNfrbdMUfjXcLrKnR4r0Ymgrjn0wVsf3Z/LBzw8NWCJnyd5HZL1Gn686IQQ+EXUk8Atixy3oXk4sj5Tn/xAfY8GhUaQzwWopzsXG8tbWWQo56ncThlnJo3Hzw8gUekTFg7s5obA21IWRA0lzNdKqCrX8I2wOk7sGznAhijQYkg1ZlpZ2eQrSg7OJ1FlIOS+VDG/ShRfVAgOG0UJCjcNIMkUPk+YiYAb+8G0SyeK3ptZbpMHFI37iudi8ss1kOQQK0S5u9LyBTESq97unL0c07/S+hF68HscgpRDCzGE4OTQYEho5+358JpuVQEUjkf5C2udOwTtiMWGKAbgI+/4vef+ynXpCMUAK7It2SLh2q/KffqIlfZsN4f/2E4btwMxjpQxCOwjFiVmoV33a76DK60pFiy4Z8Ji8qal1gWLOXUAcW6QX1LyypRuVIl0ZE/AUdI1IXO1eZBw8ZtmVJJCnDjXQyTO622HUfB7zZ1vLI6zGTcYF2NeR41PXQ1EF8LW+1yBZib2yvK+j/49mvjb0B0NbL2wVe3GY+Sik=
  app: TheDungeonGuide
  on:
    repo: Avabin/TheDungeonGuide
notifications:
  slack:
    secure: GXbqCX1FtMlrjyk8g2qwVzB1bAVuSwH4slc+ivKvaVRk654+/vuP43QNGV4vNkAwI3NMBm301/ItAhvprCwzVAk2DQ3wdlyoVIWpADNepJ6ZyIkgHV7U+TcRfUotOXS65+hCil/YgBwtvokcQalxAvM70mZgxb0zb2+xDkbryKhRQ02UYPyXQeMHpY4i+hc2/aa7vPZyXg7HOjPTkV68Uyxlgg6lXVn9KlaPas+IVpAzaYzwrXfO2jUCNNsGQRloR9Wy0llU+3eWonLnA3+lWWyF65R0sJGkpGCFAfq0FiURnpX0rCpDvIQHZKR1SZXwESVP3w/mp5NggFeXOOUGtMnMLZ9pGfb1BIr5RkQYJb6t5qgtUXRmnxOdhP2DCeZM2cnIXNxk2gVLlLtGRcXXhD6Tt55gna5RcRoObS6n7a4F3ed5EdslQA9Lz9bx7p6MbBECD1NF6WUNTTwbz9e92snsJRyAiRRO9YoVI/7vPwJepd/RICLpvfOWqFEW3sSZH9Aerw9+sDyfuovhxUwx/bS1ZStrO+XpUQ2o0tOlp262WUwmDGTIJvIq0xPGcFeLLa/BkkLv7ORzJcjnaHKYdiVngB5k9IL+j2lnoAsTIxSFOqjCgIHP2xaN+RZAaAvKV64weIUe6vwr++8fpLkSGNU1zMXrOz1hyACPaiE3WFI=
