version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
            POSTGRES_USER: test
            POSTGRES_DB: tdg_test
            POSTGRES_PASSWORD: ""

      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: tdg_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test