version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          - POSTGRES_URL: "jdbc:postgresql://localhost:5432/"
          - POSTGRES_USER: tdg
          - POSTGRES_DB: tdg
          - POSTGRES_PASSWORD: "test"

      - image: postgres:latest
        environment:
         - POSTGRES_USER: tdg
         - POSTGRES_DB: tdg
         - POSTGRES_PASSWORD: "test"

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 2m

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
